### ISSUE TITLE
Unable to create sprite

### ISSUE THREAD

**Issue by kcall** [piskelapp/piskel-website#17]
When you click on create sprite it says Sorry! Page not found.

**Comment by kcall** [comment]
![image](https://cloud.githubusercontent.com/assets/29075914/26606824/5c79fb1c-4548-11e7-9b33-e3f1bac00af7.png)

**Comment by kcall** [comment]
I tried in incognito and cleared my cache and cookies too

**Comment by kcall** [comment]
if you go to piskelapp.com/p/create it works, but it tries to direct you somewhere else first..

**Comment by juliandescottes** [comment]
Thanks for reporting the issue! 

My bad I deployed a bad version.

**Comment by juliandescottes** [comment]
Should be fixed now.

**Comment by juliandescottes** [comment]
@kcall closing as I believe this is fixed now.

**Comment by kcall** [comment]
Thanks!
