### ISSUE TITLE
Save gif without background?

### ISSUE THREAD

**Issue by EmilyMcCallum** [piskelapp/piskel-website#22]
When I save a sprite (which in the drawing editor is just the sprite on no background), it saves on a white background. It is possible to save it without a background / transparent background?

Thanks!

**Comment by juliandescottes** [comment]
GIF exports should keep a transparent background if they have less than 256 colors.

If there are more than 256 colors, you should see the following warning message when going to the GIF export panel:

![image](https://user-images.githubusercontent.com/1141550/33458011-cec38fcc-d624-11e7-8409-cfbefc777aee.png)

If the warning is not displayed but you still get the white background, can you share the sprite where this happens ?

**Comment by EmilyMcCallum** [comment]
How exactly do I make the background transparent? I think I have done, but perhaps I missed something and have done it wrong.

**Comment by juliandescottes** [comment]
Any pixel where there is no color should be transparent. For instance here: 
https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgICg5aOuCQw/edit

If you export it as GIF you get a transparent background.

**Comment by EmilyMcCallum** [comment]
Okay yeah, that's what I had thought. I'm not really sure where I'm going wrong then.
Here's the link to the sprite: https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgMCRx9zRCAw/edit

Thank you for your help!

**Comment by juliandescottes** [comment]
When I export to GIF your sprite I get a transparent background. (of course github's background is white, so can be hard to tell but if you take this GIF and put it on top of a colored background you'll see he background is transparent. 

![playerright](https://user-images.githubusercontent.com/1141550/33473981-eba0c160-d678-11e7-9dd8-b9461d605c33.gif)

Are you sure the problem is with the GIF and not with the way you are viewing it?

**Comment by EmilyMcCallum** [comment]
Thanks, I can see the background is transparent for the one you linked. It must be how I'm viewing it; I'll try using it through a different app and maybe find some solution.

Thank you so much for your help! I apologise for bothering you with an issue that wasn't with your site.

**Comment by juliandescottes** [comment]
No worries, it's always better to ask and I'm glad I could help!

**Comment by VisualNovelz** [comment]
I have the same problem I am getting an ugly white background when I upload to twitter or telegram probably other platforms as well. It is transparent but why the white background on social platforms?

**Comment by Ahryess** [comment]
Sorry to bring up an old post, but I too am having the same problem. No matter what program I open it with, it shows a white background. And actually on the gif of the man you posted above when I click on that it's not transparent for me either?

You can see the background is transparent, but when I save it it saves with a white background?
https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgOC4lu_pCgw/edit

**Comment by juliandescottes** [comment]
Hi @XziimP 

>  It is transparent but why the white background on social platforms?

Assuming the GIF really has a transparent background, most social platforms process images after you upload them. They resize them, optimize them etc... If you find that a platform supports transparent animated GIFs created from another software, but not the ones from Piskel, I can take a look. But I doubt it's specific to GIFs created by piskel, I think you'd get the same result with GIFs created from aseprite,photoshop etc... Again if you have an example I can check.  

Hi @Ahryess 

> https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgOC4lu_pCgw/edit

This sprite is private, I can't see it. Can you set it to public?

> on the gif of the man you posted above when I click on that it's not transparent for me either?

I assume your are viewing this in your browser? Browsers (or at least chrome & firefox) display images above a white background.

If you know HTML/CSS and how to use browser DevTools, you can find the <img> element in the page, change its browser-default background color, and you'll see the background of the GIF changes:
![image](https://user-images.githubusercontent.com/1141550/107488512-bec0de80-6b87-11eb-8dbd-047dc248109b.png)
gold background
![image](https://user-images.githubusercontent.com/1141550/107488555-caaca080-6b87-11eb-8d77-31a3536f1f39.png)
pink background

etc... 

So this GIF's background is transparent, guaranteed :) 

> You can see the background is transparent, but when I save it it saves with a white background?

I can't see your sprite so it's possible that you have a different issue. If I remember correctly, for GIFs which are too complex (eg too many colors) the library used to generate the GIF can't handle transparency. If that's the case, then indeed it might be saved with a white background.

**Comment by Ahryess** [comment]
Yeah I opened it in two seperate browsers and telegram and they all had the white background. I uploaded it to an online gif site though and it worked! Just had 3 false negatives that didn't convince me it was transparent xD thank you for that HTML example though, that helped it make a lot of sense.

**Comment by juliandescottes** [comment]
Thanks for taking the time to check and report back, I appreciate it @Ahryess !

**Comment by Thorbecken** [comment]
For those wondering, having a layer with transparency of 0 also counts as having a alpha layer and will turn the background white.
