### ISSUE TITLE
Piskel won't let me create a new sprite or delete anything.

### ISSUE THREAD

**Issue by Mruble** [piskelapp/piskel-website#25]
When I click either or, I get these two popups "Sorry! Unexpected error Oops. Something bad happened on our side. If you can reproduce this error, please file an issue on GitHub." and " Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."

**Comment by juliandescottes** [comment]
Do you still have the issue?

**Comment by juliandescottes** [comment]
Looks like an issue on appengine side, the google service I use to host Piskel:

https://status.cloud.google.com//incident/appengine/18003?_ga=2.190505768.-204764674.1509280074

Closing assuming this should be resolved now, but thanks for bringing this to my attention.
