### ISSUE TITLE
Piskel is not loading and is showing an error.

### ISSUE THREAD

**Issue by Sothopery** [piskelapp/piskel-website#26]
When I go to the website to create a new sprite, it takes a long time to load. It eventually does, but it gives me an error page.

**Comment by juliandescottes** [comment]
Do you still have the issue?

**Comment by juliandescottes** [comment]
Ok looks like an issue on appengine side, the google service I use to host Piskel:

https://status.cloud.google.com//incident/appengine/18003?_ga=2.190505768.-204764674.1509280074

**Comment by juliandescottes** [comment]
Closing assuming this should be resolved now, but thanks for bringing this to my attention.
