### ISSUE TITLE
Can only save one piskel to my Gallery

### ISSUE THREAD

**Issue by beamjeff** [piskelapp/piskel-website#45]
Whenever I try to save a sprite, it just saves over the sprite that was already in the Gallery, so there's always only one piskel project in my Gallery, the one that most recently saved.  Am I doing something wrong or is this a bug?  Thanks.

**Comment by juliandescottes** [comment]
Hi,

Just saving will not create a new sprite.
To create a new sprite, make sure you use the "Create sprite" button:
![image](https://user-images.githubusercontent.com/1141550/78280347-38744e80-7519-11ea-912a-41d2fb0345c7.png)

**Comment by beamjeff** [comment]
Ah, I had been thinking it worked like saving onto a hard drive and treating the Title as a filename.  I was just loading backups of previous work into the same composition and Saving with a new name, but I was just retitling the same sprite again and again.
 I guess I could give feedback and say the Save process is misleading in this respect, but if I'm the only person to have this issue then it's just on me.
Thanks for the help!
