### ISSUE TITLE
Unable to export shadows on a lower-opacity layer

### ISSUE THREAD

**Issue by PoptartPresident** [piskelapp/piskel-website#52]
Hi! I'll show an example.

I'm trying to export shadows with a lower opacity. I have them on its own layer, and made that layer a lower opacity (So the shadow isn't completely full-on black)
![Screen Shot 2020-09-14 at 5 53 32 PM](https://user-images.githubusercontent.com/28955267/93145946-3fe87800-f6b3-11ea-8c5a-a1ab5f105f4d.png)

Problem is, once I actually export the sprite on a regular PNG file, the shadow no longer holds its see-throughness. Is this a bug?

![Screen Shot 2020-09-14 at 5 55 13 PM](https://user-images.githubusercontent.com/28955267/93146047-7aeaab80-f6b3-11ea-839b-535f67a63508.png)

If not, how do I get around it? I want the shadows to keep their opacity once exported.

**Comment by juliandescottes** [comment]
Hi! 

It should work as you described. I quickly tried with a simple example (red opaque rectangle on top of a transparent red background with 0.1 opacity), exported to PNG and if I display this PNG over something else, the transparent parts are still transparent:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/1141550/93174913-208f3080-f72f-11ea-87ab-a0283d40c312.png">

I think you are previewing your PNG in the browser? In this case the browser simply displays the image on top of an opaque background, which means you won't really see the transparent parts. But they should still be there.

**Comment by PoptartPresident** [comment]
Hey thanks for replying man!

I did give it another shot, but it just doesn't seem to be working.

I'm not sure if it has to do with my computer, but I am using a macOS, (MacBook Air), and the picture I showed in the 2nd screenshot was not from a browser. I viewed it as the exported png file I described, and zoomed in using Finder before screenshotting. That is the direct exported PNG file when viewed from Finder.

The main reason I am trying to figure this out is because I want the shadow to be somewhat transparent so that it doesn't completely blacken parts of the sprites I'm making when I use the exported PNG files for RPG Maker MV. 

![Screen Shot 2020-09-16 at 2 40 10 PM](https://user-images.githubusercontent.com/28955267/93384524-8f9d7f80-f82a-11ea-9865-740eaf838b12.png)

It's so strange because it looks perfectly fine on Piskel, but it's as if the opacity doesn't carry over once you actually export the file.

**Comment by juliandescottes** [comment]
Oh wait, I see in your screenshot that both layers have the "alpha" icon displayed in yellow, which means they are both in 100% opacity.

I guess you changed layer opacity at:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/1141550/93430681-582ee180-f8c3-11ea-9cc3-1fa0ed1dc43e.png">

This is a global setting which only updates how non-selected layers are previewed in the main drawing area of Piskel. 
If you look at the preview in the top right in Piskel, you will see everything is opaque.

To update the opacity of the layer for rendering, you need to click on the alpha icon next to this layer:
<img width="165" alt="image" src="https://user-images.githubusercontent.com/1141550/93430885-a17f3100-f8c3-11ea-859c-bb107a3366a8.png">

And set an opacity lower than 1.

This should work.

**Comment by PoptartPresident** [comment]
Oh my gosh!! It worked like a charm dude!! I'll need to keep this in mind now that I'm aware of it. I've been using this program for YEARS and I never knew about that! 

Thank you!!!  :D

**Comment by juliandescottes** [comment]
You're welcome :) The UX for layer transparency in Piskel is pretty bad, not surprised you got confused by this.
