### ISSUE TITLE
Suggestion : Folders

### ISSUE THREAD

**Issue by Goosy32** [piskelapp/piskel-website#57]
Something useful would be folders to class the drawings if we have different projects at the same time.

Thanks for reading me.

**Comment by JamesTDG** [comment]
That seems like a great feature, digging through a lot of my old stuff is pretty arduous.

**Comment by vikrja** [comment]
Can probably close - with the sing-in feature going away no point in folders...

**Comment by Goosy32** [comment]
> Can probably close - with the sing-in feature going away no point in folders... 

Yes I will do it
